# pnpm-workspace.yaml

packages:
  - "packages/*"
  - "projects/*"
  - "docs/*"
  - "tools/*"
  - "templates/*"
  - "examples/*"
  - "configs/*"
onlyBuiltDependencies:
  - "@nestjs/core"
  - "@scarf/scarf"
  - "esbuild"
  - "javascript-obfuscator"
